  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/my-devops-batch06-b/myapp-repo-artifacts/pythonapp:v1', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/my-devops-batch06-b/myapp-repo-artifacts/pythonapp:v1']
    # -name: 'gcr.io'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'myappservice'
    - '--image'
    - 'us-central1-docker.pkg.dev/my-devops-batch06-b/myapp-repo-artifacts/pythonapp:v1'
    - '--region'
    - 'us-central1'
  options:
    logging : CLOUD_LOGGING_ONLY
  images:
  - 'us-central1-docker.pkg.dev/my-devops-batch06-b/myapp-repo-artifacts/pythonapp:v1'